# Generated by Django 4.2.3 on 2023-07-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_gametopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ended",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(default="Some Game", max_length=32),
            preserve_default=False,
        ),
    ]
