# Generated by Django 4.2.3 on 2023-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_game_ended_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="failed",
            field=models.DateTimeField(null=True),
        ),
    ]
